# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: theme1 #theme1
  theme_night: theme1
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo academic resume theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  copyright: 
    notice: '© {year} Petr Yatsyshin. This work is licensed under CC BY NC ND 4.0'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-gb

# Site features

# highlight_style: dracula

features:
  syntax_highlighter:
    enable: true
    extra_languages:      
      - latex
      - python
    theme_light: xcode-light
    theme_dark: xcode-light
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: '' #'https://github.com/pyatsysh/hugo-academic-netlify'
    content_dir: '' # content
    branch: '' # production
  avatar:
    gravatar: false
    shape: square # other option is circle
  comment: 
    provider: 'comment_script' # we are overriding. This is a name of file in layouts/partials/comments
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: ''
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: true
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false # this enables to add a CV icon, next to eamil, twitter, etc

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
