#!/bin/bash

echo deploying..

hugo

rsync -r public/ ../deploy

git --git-dir=../deploy/.git add -A

git --git-dir=../deploy/.git commit -m 'scripted update'

# git --git-dir=../deploy/.git status

git --git-dir=../deploy/.git push

echo done
